### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by lig** [lig/pystardict#2]

**Comment by titusfx** [comment]
I tried to install and receive an error: 

python-stardict-master$ python setup.py install
  File "setup.py", line 5
    install_requires=["struct", "types", "gzip"],

**Comment by lig** [comment]
@titusfx Very strange. There is no such code in the project. Could you please provide the whole traceback you've got?

**Comment by lig** [comment]
https://pypi.python.org/pypi/PyStarDict/0.6.1
